BOARD_WIDTH = 600
BOARD_HEIGHT = 600
GAME_MENU_1WIDTH = 650
GAME_MENU_1HEIGHT = 100
GAME_MENU_2WIDTH = 300
GAME_MENU_2HEIGHT = 750
LABEL_VERTUCAL_WIDTH = 50
LABEL_VERTICAL_HEIGHT = 600

GAME_WIDTH = GAME_MENU_1WIDTH + GAME_MENU_2WIDTH
GAME_HEIGHT = GAME_MENU_2HEIGHT
SIZE = 8
SPACE_SIZE = BOARD_WIDTH/SIZE
SQUARES_COLORS = ["white", "green"]

WHITE = True
BLACK = False

settings = {
    "AI": False,
    "TURN": True
}

SMALL_PIECE_SIZE = 20
PIECE_SIZE = 60
DEPTH = 3
MATE = 900
DRAW = 0