BOARD_WIDTH = 600
BOARD_HEIGHT = 600
GAME_MENU_1WIDTH = 650
GAME_MENU_1HEIGHT = 100
GAME_MENU_2WIDTH = 300
GAME_MENU_2HEIGHT = 750
LABEL_VERTUCAL_WIDTH = 50
LABEL_VERTICAL_HEIGHT = 600

GAME_WIDTH = GAME_MENU_1WIDTH + GAME_MENU_2WIDTH
GAME_HEIGHT = GAME_MENU_2HEIGHT
SIZE = 8
SPACE_SIZE = BOARD_WIDTH/SIZE
SQUARES_COLORS = ["white", "green"]

WHITE = True
BLACK = False

PAWN_VALUE = 100
KNIGHT_VALUE = 310
BISHOP_VALUE = 330
ROOK_VALUE = 500
QUEEN_VALUE = 900

PAWN_SCORE = 1
KNIGHT_SCORE = 3
BISHOP_SCORE = 3
ROOK_SCORE = 5
QUEEN_SCORE = 9
KING_SCORE = 100

settings = {
    "AI": False,
    "TURN": True
}

SMALL_PIECE_SIZE = 20
PIECE_SIZE = 60
DEPTH = 3
MATE = 900
DRAW = 0
PROCESSES = 16