BOARD_WIDTH = 450
BOARD_HEIGHT = 450
GAME_MENU_1WIDTH = 500
GAME_MENU_1HEIGHT = 75
GAME_MENU_2WIDTH = 100
GAME_MENU_2HEIGHT = 550
LABEL_VERTUCAL_WIDTH = 30
LABEL_VERTICAL_HEIGHT = 450

GAME_WIDTH = GAME_MENU_1WIDTH + GAME_MENU_2WIDTH
GAME_HEIGHT = GAME_MENU_2HEIGHT
SIZE = 8
SPACE_SIZE = BOARD_WIDTH/SIZE
SQUARES_COLORS = ["white", "green"]